# Generated by Django 6.0.1 on 2026-04-03 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correctness_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('quality_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('timeliness_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('communication_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('final_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('comments', models.TextField(blank=True, default='')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='task_management.taskassignment')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-evaluated_at'],
            },
        ),
    ]
