# Generated by Django 6.0.1 on 2026-01-18 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_path', models.CharField(max_length=700)),
                ('ext', models.CharField(blank=True, default='', max_length=20)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_files', to='projects.uploadversion')),
            ],
            options={
                'ordering': ['relative_path'],
                'unique_together': {('version', 'relative_path')},
            },
        ),
    ]
