# Generated by Django 6.0.1 on 2026-02-14 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='evaluator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_evaluator_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='bpmn_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='extracted_dir',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='is_well_formed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='precheck_errors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='precheck_warnings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='projectmembership',
            name='role',
            field=models.CharField(choices=[('DEVELOPER', 'Developer')], default='DEVELOPER', max_length=20),
        ),
    ]
