# Generated by Django 6.0.1 on 2026-05-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_repo_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='is_ai_agent',
            field=models.BooleanField(default=False),
        ),
    ]
