# Generated by Django 6.0.1 on 2026-02-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectfile_extracted_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='bpmn_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='is_well_formed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='precheck_errors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='precheck_warnings',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
