# Generated by Django 6.0.1 on 2026-01-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_codefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='similarity_threshold',
            field=models.FloatField(default=0.6),
        ),
    ]
