# Generated by Django 6.0.1 on 2026-02-11 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_evaluator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='codefile',
            name='ext',
            field=models.CharField(blank=True, default='', help_text='File extension (e.g., .py, .js).', max_length=30),
        ),
        migrations.AlterField(
            model_name='codefile',
            name='indexed_at',
            field=models.DateTimeField(auto_now=True, help_text='When this row was last indexed/updated.'),
        ),
        migrations.AlterField(
            model_name='codefile',
            name='project',
            field=models.ForeignKey(help_text='Project that these indexed code files belong to.', on_delete=django.db.models.deletion.CASCADE, related_name='code_files', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='codefile',
            name='relative_path',
            field=models.TextField(help_text='Relative path of the file inside the extracted project folder.'),
        ),
        migrations.AlterField(
            model_name='codefile',
            name='size_bytes',
            field=models.BigIntegerField(default=0, help_text='File size in bytes.'),
        ),
        migrations.AlterField(
            model_name='codefile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='Who uploaded the ZIP that produced this index.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='active_bpmn',
            field=models.ForeignKey(blank=True, help_text='Points to the current active BPMN upload for this project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_bpmn_projects', to='projects.projectfile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='active_code',
            field=models.ForeignKey(blank=True, help_text='Points to the current active CODE ZIP upload for this project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_code_projects', to='projects.projectfile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this project was created.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(help_text='Admin user who created the project (for auditing).', on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='evaluator',
            field=models.ForeignKey(blank=True, help_text='Evaluator assigned to this project (project-level evaluator).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluator_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='similarity_threshold',
            field=models.FloatField(default=0.6, help_text='Similarity threshold used by the semantic pipeline (0..1).'),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Upload timestamp.'),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='extracted_dir',
            field=models.TextField(blank=True, default='', help_text='For CODE uploads: extracted folder path containing source files.'),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='file_type',
            field=models.CharField(choices=[('BPMN', 'BPMN'), ('CODE', 'CODE')], help_text='Upload category: BPMN or CODE.', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='original_name',
            field=models.CharField(help_text='Original filename uploaded by the user.', max_length=255),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='project',
            field=models.ForeignKey(help_text='Project owning this upload log record.', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='stored_path',
            field=models.TextField(help_text='Stored file path (relative to MEDIA_ROOT) or absolute path (legacy).'),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='User who uploaded this file (null if user deleted).', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectmembership',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this developer was added to the project.'),
        ),
        migrations.AlterField(
            model_name='projectmembership',
            name='project',
            field=models.ForeignKey(help_text='Project that this membership belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='projectmembership',
            name='role',
            field=models.CharField(choices=[('DEVELOPER', 'Developer')], default='DEVELOPER', help_text='Project role (developer only under Option 1).', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectmembership',
            name='user',
            field=models.ForeignKey(help_text='Developer user assigned to the project.', on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
