# Generated by Django 6.0.1 on 2026-02-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_codefile_ext_alter_codefile_indexed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembership',
            name='role',
            field=models.CharField(choices=[('DEVELOPER', 'Developer'), ('EVALUATOR', 'Evaluator')], default='DEVELOPER', help_text='Project role (developer only under Option 1).', max_length=20),
        ),
    ]
