# Generated by Django 6.0.1 on 2026-03-04 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('RUNNING', 'RUNNING'), ('DONE', 'DONE'), ('FAILED', 'FAILED')], default='PENDING', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BpmnRecommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendations_text', models.TextField(blank=True, default='')),
                ('source_summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bpmn_recommendations', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='BpmnTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bpmn_tasks', to='projects.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CodeArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_uid', models.CharField(db_index=True, max_length=512)),
                ('file_path', models.CharField(blank=True, default='', max_length=512)),
                ('language', models.CharField(blank=True, default='python', max_length=64)),
                ('symbol', models.CharField(blank=True, default='', max_length=256)),
                ('kind', models.CharField(choices=[('function', 'function'), ('method', 'method'), ('class', 'class')], default='function', max_length=32)),
                ('raw_snippet', models.TextField(blank=True, default='')),
                ('calls', models.JSONField(blank=True, default=list)),
                ('writes', models.JSONField(blank=True, default=list)),
                ('returns', models.JSONField(blank=True, default=list)),
                ('exceptions', models.JSONField(blank=True, default=list)),
                ('developer_id', models.CharField(blank=True, max_length=128, null=True)),
                ('summary_text', models.TextField(blank=True, default='')),
                ('structured_summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_artifacts', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_ref', models.CharField(blank=True, default='', max_length=800)),
                ('similarity_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('MATCHED', 'MATCHED'), ('MISSING', 'MISSING'), ('EXTRA', 'EXTRA')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='projects.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='analysis.bpmntask')),
            ],
            options={
                'ordering': ['-similarity_score', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='bpmntask',
            constraint=models.UniqueConstraint(fields=('project', 'task_id'), name='uniq_project_taskid'),
        ),
        migrations.AddIndex(
            model_name='codeartifact',
            index=models.Index(fields=['project', 'code_uid'], name='analysis_co_project_1415db_idx'),
        ),
        migrations.AddIndex(
            model_name='codeartifact',
            index=models.Index(fields=['project', 'file_path'], name='analysis_co_project_04e0f8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='codeartifact',
            unique_together={('project', 'code_uid')},
        ),
    ]
