# Generated by Django 6.0.1 on 2026-03-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpmntask',
            name='summary_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
