# Generated by Django 6.0.1 on 2026-05-05 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeartifact',
            name='structured_summary',
        ),
        migrations.AddField(
            model_name='bpmntask',
            name='incoming_nodes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bpmntask',
            name='outgoing_nodes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bpmntask',
            name='summary_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bpmntask',
            name='task_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.CreateModel(
            name='BpmnRecommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendations_text', models.TextField(blank=True, default='')),
                ('source_summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bpmn_recommendations', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='CodeEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code_artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='analysis.codeartifact')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_embeddings', to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'code_artifact')},
            },
        ),
        migrations.CreateModel(
            name='TaskEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bpmn_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='analysis.bpmntask')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_embeddings', to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'bpmn_task')},
            },
        ),
    ]
