# Generated by Django 6.0.1 on 2026-02-16 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('projects', '0002_projectfile_extracted_dir'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_uid', models.CharField(db_index=True, max_length=512)),
                ('file_path', models.CharField(blank=True, default='', max_length=512)),
                ('language', models.CharField(blank=True, default='python', max_length=64)),
                ('symbol', models.CharField(blank=True, default='', max_length=256)),
                ('kind', models.CharField(choices=[('function', 'function'), ('method', 'method'), ('class', 'class')], default='function', max_length=32)),
                ('raw_snippet', models.TextField(blank=True, default='')),
                ('calls', models.JSONField(blank=True, default=list)),
                ('writes', models.JSONField(blank=True, default=list)),
                ('returns', models.JSONField(blank=True, default=list)),
                ('exceptions', models.JSONField(blank=True, default=list)),
                ('developer_id', models.CharField(blank=True, max_length=128, null=True)),
                ('summary_text', models.TextField(blank=True, default='')),
                ('structured_summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_artifacts', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='CodeEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField()),
                ('code_artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.codeartifact')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_embeddings', to='analysis.analysisrun')),
            ],
        ),
        migrations.CreateModel(
            name='SimilarityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255)),
                ('score', models.FloatField()),
                ('code_artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.codeartifact')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.analysisrun')),
            ],
        ),
        migrations.AddIndex(
            model_name='codeartifact',
            index=models.Index(fields=['project', 'code_uid'], name='analysis_co_project_1415db_idx'),
        ),
        migrations.AddIndex(
            model_name='codeartifact',
            index=models.Index(fields=['project', 'file_path'], name='analysis_co_project_04e0f8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='codeartifact',
            unique_together={('project', 'code_uid')},
        ),
    ]
