# Generated by Django 6.0.1 on 2026-01-18 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('projects', '0003_project_similarity_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='BpmnTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bpmn_tasks', to='projects.uploadversion')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('version', 'task_id')},
            },
        ),
    ]
