# Generated by Django 6.0.1 on 2026-04-03 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_bpmntask_summary_text'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BpmnRecommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendations_text', models.TextField(blank=True, default='')),
                ('source_summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bpmn_recommendations', to='projects.project')),
            ],
        ),
    ]
