# Generated by Django 6.0.1 on 2026-01-18 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_bpmntask'),
        ('projects', '0003_project_similarity_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_ref', models.CharField(blank=True, default='', max_length=800)),
                ('similarity_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('MATCHED', 'MATCHED'), ('MISSING', 'MISSING'), ('EXTRA', 'EXTRA')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='analysis.bpmntask')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='projects.uploadversion')),
            ],
            options={
                'ordering': ['-similarity_score', '-created_at'],
            },
        ),
    ]
