# Generated by Django 6.0.1 on 2026-05-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_remove_codeartifact_structured_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpmntask',
            name='ai_suitability',
            field=models.CharField(choices=[('RECOMMENDED', 'Recommended'), ('NEUTRAL', 'Neutral'), ('NOT_RECOMMENDED', 'Not Recommended'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='bpmntask',
            name='ai_suitability_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bpmntask',
            name='ai_suitability_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='matched_summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
