# Generated by Django 6.0.1 on 2026-04-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_bpmnrecommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpmntask',
            name='incoming_nodes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bpmntask',
            name='outgoing_nodes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
