# Generated by Django 6.0.1 on 2026-04-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_bpmntask_incoming_nodes_bpmntask_outgoing_nodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpmntask',
            name='task_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
