# Generated by Django 6.0.1 on 2026-04-08 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_bpmntask_task_type'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code_artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='analysis.codeartifact')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_embeddings', to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'code_artifact')},
            },
        ),
        migrations.CreateModel(
            name='TaskEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bpmn_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='analysis.bpmntask')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_embeddings', to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'bpmn_task')},
            },
        ),
    ]
