# Generated by Django 6.0.1 on 2026-04-10 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_add_embedding_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeartifact',
            name='structured_summary',
        ),
    ]
